# http://doc.rultor.com/
docker:
  image: "yegor256/java8"

env:
  MAVEN_OPTS: "-XX:MaxPermSize=256m -Xmx1g"

merge:
  commanders:
    - aistomin
  script: |-
    java -version
    mvn -version
    mvn clean install package