dist: trusty
language: java
jdk:
  - oraclejdk15
branches:
  only:
    - master
env:
  global:
    - MAVEN_OPTS="-XX:MaxPermSize=512m -Xmx2g"
    - CODECOV_TOKEN="596cfecd-20fc-44be-a7ac-ac7a46e2bb48"
script: ./build.sh